openapi: 3.0.0
info:
  description: >
    _This document describes the REST API of Ark Automate._
    Ark Automate is a platform that allows office users and software developers to automate business or everyday processes by simply sketching the steps of their process. By using simple flowcharts or powerful BPMN in their process outlines, users can create small software solutions using RPA that finish their tasks much faster and more reliably.
  version: 1.0.0
  title: Ark-Automate API

servers:
  - url: '{protocol}://{server}/api/v1'
    variables:
      protocol:
        default: https
        enum: [http, https]
      server:
        default: localhost:5000

tags:
  - name: RPA-Functionalities
    description: Operations about rpa supported applications, tasks and parameters
  - name: Robots
    description: Operations about robots

paths:
  #### RPA Functionalities ####
  /functionalities:
    # used to be: GET /rpa-framework/commands/get-available-applications
    get:
      tags:
        - RPA-Functionalities
      summary: Get all functionality objects including task, application and parameters
      operationId: getFunctionalities
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Functionalities'
  /functionalities/applications:
    # used to be: GET /rpa-framework/commands/get-available-applications
    get:
      tags:
        - RPA-Functionalities
      summary: Get all applications that ark automate supports
      operationId: getApplications
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Applications'
  /functionalities/{application}/tasks:
    parameters:
      - name: application
        in: path
        description: The name of an application
        required: true
        schema:
          $ref: '#/components/schemas/Applications'
    # used to be: GET /rpa-framework/commands/get-available-tasks-for-application?application=Browser
    get:
      tags:
        - RPA-Functionalities
      summary: Gets all the tasks to execute for an application
      operationId: getTasks
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tasks'
        404:
          description: Not Found
  #### Robots ####
  /robots/{robotId}:
    parameters:
      - name: robotId
        in: path
        description: The id of a robot
        required: true
        schema:
          $ref: '#/components/schemas/RobotIds'
    # used to be: /ssot/:id
    get:
      tags:
        - Robots
      summary: Get a robot with a specific id
      operationId: getSpecificRobot
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Robots'
    # used to be: POST /overwriteRobot/78d09f66d2ed466cf20b06f7
    put:
      tags:
        - Robots
      summary: Overwrite the existing robot with an updated one
      operationId: overwriteRobot
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Robots'
        description: updated Robot object
        required: true
      responses:
        204:
          description: No Content
        400:
          description: Bad Request
  /robots/{robotId}/robotCode:
    parameters:
      - name: robotId
        in: path
        description: The id of a robot
        required: true
        schema:
          $ref: '#/components/schemas/RobotIds'
    # used to be: /parser/getForId/:robotId
    get:
      tags:
        - Robots
      summary: Get the robot framework code of a specific robot
      operationId: getRobotCode
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RobotCode'
  /robots/{robotId}/robotName:
    parameters:
      - name: robotId
        in: path
        description: The id of a robot
        required: true
        schema:
          $ref: '#/components/schemas/RobotIds'
    # used to be: /renameRobot?id=78d09f66d2ed466cf20b06f7&newName=Bot+Browser
    patch:
      tags:
        - Robots
      summary: Updates the name of a robot
      operationId: setRobotName
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RobotNameObjects'
        description: Object with new robot name
        required: true
      responses:
        204:
          description: No Content
        400:
          description: Bad Request
  /robots/userAccess:
    # used to be: GET /shareRobotWithUser?userId=78d09f66d2ed466cf20b06f7&robotId=78d09f66d2ed466cf20b06f7
    post:
      tags:
        - Robots
      summary: Share a robot with a user
      operationId: createUserAccessObject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAccessObjects'
        description: Object that connects a user with a robot
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAccessObjects'
        400:
          description: Bad Request
  /robots/{userId}:
    parameters:
      - name: userId
        in: path
        description: The id of a user
        required: true
        schema:
          $ref: '#/components/schemas/ObjectIds'
    # used to be: GET ssot/getAvailableRobotsForUser/78d09f66d2ed466cf20b06f7
    get:
      tags:
        - Robots
      summary: Get all robots for a specific user
      operationId: getRobotsForUser
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - _id
                    - robotName
                  properties:
                    _id:
                      $ref: '#/components/schemas/RobotIds'
                    robotName:
                      $ref: '#/components/schemas/RobotNames'
    # used to be: GET /createNewRobot?userId=78d09f66d2ed466cf20b06f7&robotName=NewRobot
    post:
      tags:
        - Robots
      summary: Create a new robot for a specific user
      operationId: createRobotForUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - robotName
              properties:
                userId:
                  $ref: '#/components/schemas/ObjectIds'
                robotName:
                  $ref: '#/components/schemas/RobotNames'
        description: Object that contains the new robotObject and a new userAccessObject
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                required:
                  - robotId
                  - robotName
                properties:
                  robotId:
                    $ref: '#/components/schemas/RobotIds'
                  robotName:
                    $ref: '#/components/schemas/RobotNames'
        400:
          description: Bad Request
  /robots/parameters:
    # used to be: POST /ssot/updateManyParameters/
    put:
      tags:
        - Robots
      summary: Overwrite existing parameter objects with updated one's
      operationId: overwriteParameters
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - parameterObjectsList
              properties:
                parameterObjectsList:
                  type: array
                  items:
                    $ref: '#/components/schemas/Parameters'
        description: updated parameter object
        required: true
      responses:
        204:
          description: No Content
        400:
          description: Bad Request
  /robots/parameters/{robotId}:
    parameters:
      - name: robotId
        in: path
        description: The id of a robot
        required: true
        schema:
          $ref: '#/components/schemas/RobotIds'
    # used to be: GET /getAllParameters/604f537ed699a2eb47433184'
    get:
      tags:
        - Robots
      summary: Get all parameter objects for a specific robot
      operationId: getParametersForRobot
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Parameters'
  /robots/rpaattributes:
    # used to be: POST /ssot/updateManyAttributes/
    put:
      tags:
        - Robots
      summary: Overwrite existing rpa attribute objects with updated one's
      operationId: overwriteAttributes
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - attributeObjectList
              properties:
                attributeObjectList:
                  type: array
                  items:
                    $ref: '#/components/schemas/RPAAttributes'
        description: updated attributes object
        required: true
      responses:
        204:
          description: No Content
        400:
          description: Bad Request
  /robots/rpaattributes/{robotId}:
    parameters:
      - name: robotId
        in: path
        description: The id of a robot
        required: true
        schema:
          $ref: '#/components/schemas/RobotIds'
    # used to be: GET /getAllAttributes/604f537ed699a2eb47433184'
    get:
      tags:
        - Robots
      summary: Get all rpa attribute objects for a specific robot
      operationId: getAttributesForRobot
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RPAAttributes'
components:
  schemas:
    #### General ####
    ObjectIds:
      type: string
      minLength: 1
      example: 6061d5627dee5516b3824ade
    #### RPA-Functionalities ####
    Functionalities:
      type: object
      required:
        - _id
        - Application
        - Task
        - Code
      properties:
        _id:
          $ref: '#/components/schemas/ObjectIds'
        Application:
          $ref: '#/components/schemas/Applications'
        Task:
          $ref: '#/components/schemas/Tasks'
        Code:
          $ref: '#/components/schemas/Tasks'
        ouputValue:
          type: boolean
        inputVars:
          type: object
          required:
            - name
            - type
            - isRequired
            - infoText
            - index
          properties:
            name:
              type: string
              example: visible
            type:
              type: string
              example: Boolean
            isRequired:
              type: boolean
            infoText:
              type: string
              example: Show window after opening
            index:
              type: integer
              example: 0
    Applications:
      type: string
      example: Excel.Files
    Tasks:
      type: string
      example: Open Workbook
    #### Robots ####
    RobotCode:
      type: string
    RPAAttributes:
      type: object
      required:
        - robotId
        - activityId
        - rpaApplication
        - rpaTask
      properties:
        robotId:
          $ref: '#/components/schemas/RobotIds'
        activityId:
          $ref: '#/components/schemas/ActivityIds'
        rpaApplication:
          $ref: '#/components/schemas/Applications'
        rpaTask:
          $ref: '#/components/schemas/Tasks'
    Parameters:
      type: object
      required:
        - activityId
        - robotId
      properties:
        activityId:
          $ref: '#/components/schemas/ActivityIds'
        robotId:
          $ref: '#/components/schemas/RobotIds'
        outputVariable:
          type: string
          example: Activity_0n140xq_output
        rpaParameters:
          type: array
          items:
            $ref: '#/components/schemas/singleParameterObjects'
    singleParameterObjects:
      type: object
      required:
        - name
        - value
        - requireUserInput
        - type
        - isRequired
        - infoText
        - index
      properties:
        name:
          type: string
          example: visible
        value:
          type: boolean
        requireUserInput:
          type: boolean
        type:
          type: string
          example: Boolean
        isRequired:
          type: boolean
        infoText:
          type: string
          example: Show window after opening
        index:
          type: integer
          example: 1
    UserAccessObjects:
      type: object
      required:
        - AccessLevel
        - robotId
        - userId
      properties:
        AccessLevel:
          type: string
          example: ReadWrite
        robotId:
          $ref: '#/components/schemas/RobotIds'
        userId:
          $ref: '#/components/schemas/ObjectIds'
    RobotNameObjects:
      type: object
      required:
        - newRobotName
      properties:
        newRobotName:
          type: string
          minLength: 1
          example: Automating emails
    RobotIds:
      type: integer
      example: 606199015d691786a44a608f
    EventIds:
      type: string
      minLength: 1
      example: Event_0ay5426
    ActivityIds:
      type: string
      minLength: 1
      example: Activity_0ay5427
    ElementIds:
      type: string
      minLength: 1
      example: Event_0ay5426 or Activity_0ay5427
    RobotNames:
      type: string
      example: Automate morning emails
    RobotElements:
      type: object
      required:
        - predecessorIds
        - successorIds
        - _id
        - type
        - name
        - id
      properties:
        predecessorIds:
          type: array
          items:
            $ref: '#/components/schemas/ElementIds'
        successorIds:
          type: array
          items:
            $ref: '#/components/schemas/ElementIds'
        _id:
          $ref: '#/components/schemas/ObjectIds'
        type:
          type: string
          example: INSTRUCTION
        name:
          type: string
          example: Fill in current sales projections
        id:
          $ref: '#/components/schemas/ActivityIds'
    Robots:
      type: object
      required:
        - _id
        - robotName
      properties:
        # Question: how to deal with automatically generated ids that are relevant for get but irrelevant for post
        _id:
          $ref: '#/components/schemas/RobotIds'
        starterId:
          $ref: '#/components/schemas/EventIds'
        robotName:
          $ref: '#/components/schemas/RobotNames'
        elements:
          type: array
          items:
            $ref: '#/components/schemas/RobotElements'
